repository:
  name: module-azurerm-vnet
  description: Terraform module which creates VNET resources on Azure.
  homepage: https://github.com/aztfmods/module-azurerm-vnet
  topics: module, vnet
  private: true
  has_issues: true
  has_projects: true
  has_wiki: true
  has_downloads: true
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

labels:
  - name: integration
    color: '#FEF2C0'
    description: integration
  - name: module
    color: '#7BE107'
    description: module
  - name: 'needs refinement'
    color: '#B533B3'
    description: 'needs refinement'
  - name: bug
    color: '#B60205'
    description: bug
  - name: 'blocked'
    color: '#d93f0b'
    description: 'blocked'

branches:
  - name: main
    protection:
      required_pull_request_reviews:
        #required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        dismissal_restrictions:
          users: []
          teams: []
      required_status_checks:
        strict: true
        contexts: []
      enforce_admins: true
      required_linear_history: true
      restrictions:
        apps: []
        users: []
        teams: []